=== DanielaAndreaGonzalez/JAVA_NETBEANS_PROYECTOS/Carnet/src/Carnet/Carnetestudiantil.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Carnetestudiantil.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE estudiante SYSTEM "Carnetestudiantil.dtd">

    <estudiante>
    ...
    </estudiante>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT estudiante (foto|programa|identificacion|apellido|nombre|codigo|sede|logo|titulo)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT titulo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT logo EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sede (datosede|sedenombre)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sedenombre (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT datosede (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT codigo (codigodato|codigonombre)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT codigonombre (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT codigodato (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nombre (datonombre|nombreest)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nombreest (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT datonombre (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT apellido (datoapellido|apellidoeti)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT apellidoeti (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT datoapellido (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT identificacion (datoid|id)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT id (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT datoid (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT programa (prog|programanom)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT programanom (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT prog (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT foto (fotoimg|fotoeti)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fotoeti (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fotoimg EMPTY>

=== DanielaAndreaGonzalez/JAVA_NETBEANS_PROYECTOS/Carnet/src/Carnet/Carnetestudiantil.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE estudiante SYSTEM "carnetestudiantil.dtd">
<?xml-stylesheet href="Carnetestudiantil.css" type="text/css" ?>

<estudiante>
    <titulo>
        Universidad del Valle
    </titulo>
    <logo>
     </logo>
<sede>
      <sedenombre>
            Sede : 
        </sedenombre>
        <datosede>
            Caicedonia 
        </datosede>   
</sede>
 <codigo>
        <codigonombre>
          Codigo:    
        </codigonombre>
        <codigodato>
           1761910 
        </codigodato>
  </codigo>   
   <nombre>
         <nombreest>
         Nombre:
        </nombreest>
        <datonombre>
            Daniela Andrea
        </datonombre> 
  </nombre>
  <apellido>
      <apellidoeti>
          Apellidos:
      </apellidoeti>
      <datoapellido>
          GONZÁLEZ HENAO
      </datoapellido>
  </apellido>
    <identificacion>
        <id>
           Identificación: 
        </id>
        <datoid>
           1115195022 
        </datoid>
    </identificacion>
    <programa>
     <programanom> Programa: 
         
     </programanom>
        <prog>
  Tecnología en Sistemas de
      Información
        </prog>
    </programa>    
    <foto>
        <fotoeti>
            Estudiante
        </fotoeti>
        <fotoimg>
        </fotoimg>
    </foto>
</estudiante>
